update dependencies fix sqlx-mysql assertion failed: len < 0xFF_FF_FF
ipfs-force-community/gpuproxy pull request #49
Opened 2024-01-08 09:23 UTC by rickiey

upgrade rust-toolchain sea_orm *
fix column_type Binary => Binary(BlobSize::Long)

2024-01-08 09:49 UTC, Fatman13 commented
多谢 PR！🙏

2024-01-08 10:21 UTC, 0x5459 commented
我发现 simplelog 和 tabled 依赖的版本用的是"*" 号。可能给你升级依赖带来了困扰。

https://github.com/ipfs-force-community/gpuproxy/blob/3983b30386c8f8700565a866fb1a175b9ee555ab/gpuproxy/Cargo.toml#L36
https://github.com/ipfs-force-community/gpuproxy/blob/3983b30386c8f8700565a866fb1a175b9ee555ab/gpuproxy/Cargo.toml#L49

你能将其修改为以下版本吗？
```toml
simplelog = "0.12.0"
tabled = { version = "0.14.0", features = ["color"] }
```

2024-01-09 02:39 UTC, 0x5459 requested changes
最后一点点小问题

2024-01-09 02:39 UTC, 0x5459 commented on migration/Cargo.toml
> +sea-schema = { version = "0.12.0-rc.2", default-features = false}
```suggestion
sea-schema = { version = "0.12.0", default-features = false}
```

2024-01-09 02:39 UTC, 0x5459 commented on gpuproxy/src/cli/tasks.rs
> +    // table.with(Style::ascii());
这里为什么要注释掉呢？

2024-01-09 02:39 UTC, 0x5459 commented on gpuproxy/src/cli/worker_states.rs
> +        // .with(Style::ascii());
Same as above

2024-01-09 02:39 UTC, 0x5459 commented on gpuproxy/src/cli/tasks.rs
> +        // .with(Style::ascii());
Same as above

2024-01-09 03:16 UTC, rickiey commented on gpuproxy/src/cli/tasks.rs
> +        // .with(Style::ascii());
这个版本的 tabled 使用`.with(Style::ascii())` 会出现 `creates a temporary value which is freed while still in use` 问题，当时注释掉了，我等会处理下，sea-schema 升级到 0.14.1，和sea_orm_cli的依赖保持一致

2024-01-09 05:29 UTC, 0x5459 approved these changes
LGTM!

2024-01-09 05:29 UTC, merged